### ISSUE TITLE
Wow!

### ISSUE THREAD

**Issue by antfu** [wenyan-lang/book#1]
This definitely desires to open an issue to say Wow! You are so talented on this!

I already love your prologue so much and now this comes up!

It's a shame that I can help little about the content itself. But I think I can help with the building system. Wuepress may not be very suitable for this and can be overkill. I think we can build our own tools for this. Anyway, that's something to be taken up later. :)

Awesome job! I will try to read them more thoroughly then. 👍

**Comment by LingDong-** [comment]
Glad you like it! I'm envisioning some vertical text + horizontal scrolling thing. I'll focus on the content first and later see how we can present it best. :D

**Comment by antfu** [comment]
That's it! I always try to support vertical text for wenyan. But it seems no luck for Codemirror / vscode (at least no easy ways). It's very fit and doable for the book. I will do some researches as well.

**Comment by antfu** [comment]
I think I found some interesting references:

http://tategaki.github.io/en/
http://tategaki.github.io/awards/
https://w3c.github.io/i18n-drafts/articles/vertical-text/index.en

**Comment by antfu** [comment]
I have made an experiment https://codepen.io/antfu/full/zYxJwEL

**Comment by LingDong-** [comment]
👍Works great. I'm thinking maybe we can make the whole book one continuous scroll, and when you click on TOC it fast-forward to the section. Not sure how much this would hurt performance.
Don't worry too much about it right now, the cosmetics is the easy part, the content is the "brain-burner"  ;)

**Comment by antfu** [comment]
Haha I can see it took up all your energy. But the content is truly awesome. Take your time and looking forward to it! 😄

**Comment by LingDong-** [comment]
And thanks so much for all your help with the code & development stuff while I'm delving into classical Chinese :D
