### ISSUE TITLE
第三章关于减法中“於”的用法的叙述有误

### ISSUE THREAD

**Issue by User670** [wenyan-lang/book#10]
减法没有交换律，因此“以”和“於”不等价。
```
減二以一。書之。 //2-1 = 1
減二於一。書之。 //1-2 = (-1)
```
[03 算術第三.md](https://github.com/wenyan-lang/book/blob/master/03%20%E7%AE%97%E8%A1%93%E7%AC%AC%E4%B8%89.md) 第36行 `加減乘有交換率者。於通以。`可以改一下了。

**Comment by LingDong-** [comment]
Now fixed: 9824162161c67c96aca2406d49b84ad0770ef5d2

Thanks a lot for pointing out! What a silly mistake ;)

**Comment by yezhiyi9670** [comment]
The website is still wrong so far.

**Comment by LingDong-** [comment]
@yezhiyi9670 the site is now updated. The automatic site rebuild was not triggered for some reason, so I manually did it. Thanks for pointing out!
