### ISSUE TITLE
別言語者另有『引號』 why not? 

### ISSUE THREAD

**Issue by hcchengithub** [wenyan-lang/book#25]
「「雙引號」」者。所以別言語於其他也。微是。不能別歧義也。
然
唯別言語者另有『引號』 why not?

**Comment by LingDong-** [comment]
In wenyan-lang, both `「「」」` and `『』` are accepted and equivalent. `「「」」` is only the stylistic choice here. (See discussion https://github.com/wenyan-lang/wenyan/issues/81#issuecomment-566934115) 
In the rendered versions of the book, e.g. https://book.wy-lang.org/, you can see that `「「` is indeed rendered very similar to `『`.
Thanks.

**Comment by hcchengithub** [comment]
善
