### ISSUE TITLE
关于pr #29

### ISSUE THREAD

**Issue by NFLS-1963** [wenyan-lang/book#30]
不知道怎么在 book.wy-lang.org 上改。知道的大佬请帮忙再交个pr。

**Comment by NFLS-1963** [comment]
#29

**Comment by LingDong-** [comment]
Thanks a lot! Now merged and site updated:

![image](https://user-images.githubusercontent.com/7929704/132250960-62b5e3a1-f631-4954-b7e3-a1aa4d681c3d.png)
