### ISSUE TITLE
wrong link in README.md

### ISSUE THREAD

**Issue by DGCK81LNN** [wenyan-lang/book#5]
https://github.com/wenyan-lang/book#read-online

```markdown
## [Read Online](https:/book.wy-lang.org)
```
this link currently goes to https://github.com/book.wy-lang.org because of missing slash, should be:
```markdown
## [Read Online](https://book.wy-lang.org)
```

**Comment by LingDong-** [comment]
Thanks a lot for pointing this out!

Fixed: 03606e59dcca5fcb3bab259e80cdc5f6af2fe110
and again: 01c1a48b750936f97da640f738c380f2ddd14478
