### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by ghost** [wenyan-lang/book#7]
格物一篇中有言『欲行是術。必先得**而**言』於九十頁。似為筆誤。望改之。

**Comment by ghost** [comment]
还有就是因为书是从右往左读的，建议把pdf的顺序也调转过来，以便阅读

**Comment by LingDong-** [comment]
> 格物一篇中有言『欲行是術。必先得而言』於九十頁。似為筆誤。望改之。

Thanks for pointing out! Now fixed: 6f5ed98b3c4c27839a6362807e175e9aa93f1a66

Re-generating the PDF is bit of a hassle, I plan to do that at end of each week, when I'll have collected a couple of errors. But the markdown and HTML versions are updated instantaneously. Hope you don't mind.

> 还有就是因为书是从右往左读的，建议把pdf的顺序也调转过来，以便阅读

Do you mean reverse the page order of entire book, so the front cover is on the last page and you scroll upwards? That would be kinda weird, I haven't seen that done elsewhere in old Chinese book digitization. Or are you using a PDF reader that supports horizontal scrolling? If so, I may consider generating two versions of PDF for vertical and horizontal scrolling readers.

Thanks again for spotting the typo and the suggestion!

**Comment by ghost** [comment]
Yes, that’s what I mean. But it’s not so important a urgent problem, and I think vertical scrolling is not so bad, so if my suggestion is weird  (I haven’t seen any digitized old book before!)  you don’t have to fix it.

**Comment by ghost** [comment]
I have another question yet. The丹道mentioned at the end of the book is machine learning, right?

**It seems that wy-lang supports machine learning?!**

Just guessing.

**Comment by LingDong-** [comment]
> Yes, that’s what I mean.

Totally reasonable, will make a horizontal scrolling version in the next release.

> It seems that wy-lang supports machine learning?!

Haha I'm currently working on a tensorflow.js wrapper for wenyan. It already supports training and testing basic convnets now but still very much work-in-progress. At first I was trying to write an entire chapter about it, but figured it's too complex to explain all the concepts from scratch.

I'll make the ML library for wenyan public soon :)

**Comment by ghost** [comment]
Very want to learn ML😀😀 wish you can make a success.

**Comment by ghost** [comment]
https://cdn.jsdelivr.net/gh/wenyan-lang/book/assets/wenyan-book.pdf
The book cover is weird.
Is that my browser’s fault?

**Comment by LingDong-** [comment]
> The book cover is weird.

Oops, I think you're seeing the old design, which was replaced a couple of days ago. jsdelivr is caching the old file. If possible, check out `./assets/wenyan-book.pdf` directly on Github.

Also, you can force jsdelivr to give you the newer version by adding the commit hash, like so:

https://cdn.jsdelivr.net/gh/wenyan-lang/book@cd38eb03143e8a672e93abe2a0b9107bcbde5eaf/assets/wenyan-book.pdf


> Very want to learn ML😀😀 wish you can make a success.

Thanks!

**Comment by ghost** [comment]
Thanks for your useful help.
